---
# tasks file for apache_installer
  - name: Ping all servers
    ping:

  - name: Install apache2
    yum:
      pkg: httpd
      state: latest

  - name: Enable Apache Services
    service: name=httpd state=started

  - name: Open port 80
    firewalld: service=http permanent=true state=enabled

  - name: start firewall service
    service: name=firewalld state=restarted 

  - name: Say me ip a
    shell: ip a
